#!/bin/bash -i

source $HOME/.bashrc

sleep 10

rosservice call /gazebo/set_link_state "link_state:
  link_name: 'velodyne_laser_spin'
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.1
  reference_frame: 'base_link'"
